language: c
sudo: true
dist: xenial

os:
  - linux
  - osx
  - windows

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      elif [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe";
        sudo apt-get update;
        sudo apt -q install fpc;
      else
        choco install -y freepascal;     
      fi

script:
 - fpc
 - fpc -vtu GLPT.pas 

notifications:
  email:
    on_success: false
    on_failure: change
